BUG/MEDIUM: api: Prevent zpki from waiting indefinitely on stdin
If a CA folder <olddir> is removed / renamed, the server can accumulate
zpki processes waiting on input for a user confirmation to answer the
question "Create CA storage directory '<olddir>' (y/n):".

The first thing is we can close stdin or pass /dev/null to it when
calling zpki. However zpki's yesno() function does not check read return
code and will go in an infinite loop. To fix that we can make it abort
if read fails. Also, since we can check if stdin is a terminal (there is
already a $HAS_TTY variable for that), we'd better just abort is YES=1
is not present in env.

diff --git a/zpki b/zpki
--- a/zpki
+++ b/zpki
@@ -212,8 +212,10 @@ function debug() {
 function yesno() {
   local QUESTION="$1" ; shift
   [[ $YES == 1 ]] && return 0
+  [[ $HAS_TTY == 1 ]] || fatal "Need YES=1 or stdin, abort"
   while : ; do
     echo -n "$QUESTION (y/n): " && read
+    (( $? == 0 )) || fatal "Read on stdin failed, abort"
     case $REPLY in
       [Yy]|[Yy][Ee]|[Yy][Ee][Ss]) return 0 ;;
       [Nn]|[Nn][Oo]) return 1 ;;
